### ISSUE TITLE
GUI OPTION

### ISSUE THREAD

**Issue by prats2018** [makechip/stdf2xls4#1]
Hi,
Can you tell how we can check the view in gui. I have tried -gui. But it doesnot work. My java version is openjdk version "1.8.0_191".  Can you update the gui usage option too.

Thanks
Prats

**Comment by makechip** [comment]
Hi -
Sorry -I don't usually check this page because I just use github to copy the program
to my customers.  I don't really support the GUI option.  I just added it as an experiment.
